### ISSUE TITLE
Не экспортируется в .pfx самоподписанный сертификат с паролем к ключевому контейнеру

### ISSUE THREAD

**Issue by nshdigt** [TrustedPlus/GUI-Trusted-eSign-iOS#24]
Не экспортируется  самоподписанный сертификат с паролем на закрытый ключ в .pfx. В журнале операций нет сообщений.
Шаги:
1. Создать самоподписанный сертификат с паролем (не пустым) к ключевому контейнеру.
2. Экспортировать этот сертификат с закрытым ключом.
3. Ввести пароль к контейнеру (почему то два раза)
Ничего не происходит.
Сертификат должен экспортироваться

**Comment by IsaacTaitor** [comment]
((action : {action}) => {
                              () => RNFS.unlink(path);
                              if (action.action === Share.dismissedAction) {
                                 Alert.alert("Отправка файла была отклонена"
);
                              } else {
                                 Alert.alert("Файл успешно отправлен");
                              }
                           })


2018-05-30 16:31 GMT+03:00 Shalagina Natalya <notifications@github.com>:
